language: python
python:
  - 2.7
  - 3.4
sudo: false
install: pip install coveralls flake8
script:
  - flake8 pkaaw
  - flake8 tests
  - coverage run --source=pkaaw setup.py test
after_success: coveralls